// frontends/vue/src/App.vue
<script setup>
import Todo from "./components/Todo.vue";
import { ref, onMounted } from "vue";
import { addTodo, getTodos } from "todos-client";

const data = ref(null);
const error = ref(null);
const text = ref("");

function mutate() {
  getTodos()
    .then((d) => (data.value = d))
    .catch((e) => (error.value = e));
}

function handleAdd() {
  addTodo({ text: text.value, done: false })
    .then(mutate)
    .catch(() => {
      alert("Failed to add");
    });
}

onMounted(mutate);
</script>

<template>
  <p v-if="error">An error occurred while fetching data</p>
  <p v-else-if="!data">Loading...</p>
  <template v-else>
    <h1>To Do</h1>
    <h2>Remaining Tasks</h2>
    <ul>
      <li v-for="todo in data">
        <Todo :todo="todo" @on-change="mutate" />
      </li>
    </ul>
    <h2>New Task</h2>
    <form @submit.prevent="handleAdd">
      <input v-model="text" required />
      <button>Add</button>
    </form>
  </template>
</template>

// frontends/react/src/App.js
import React, { useCallback, useEffect, useState } from "react";
import { addTodo, getTodos } from "todos-client";
import Todo from "./Todo";

export default function App() {
  const [data, setData] = useState();
  const [error, setError] = useState();
  const [text, setText] = useState("");

  const mutate = useCallback(() => {
    getTodos().then(setData).catch(setError);
  }, []);

  useEffect(mutate, [mutate]);

  function handleAdd(event) {
    event.preventDefault();

    addTodo({ text, done: false })
      .then(mutate)
      .catch(() => {
        alert("Failed to add");
      });
  }

  if (error) return <p>An error occurred while fetching data</p>;
  if (!data) return <p>Loading...</p>;

  return (
    <>
      <h1>To Do</h1>
      <h2>Remaining Tasks</h2>
      <ul>
        {data.map((todo) => (
          <li key={todo.id}>
            <Todo todo={todo} onChange={mutate} />
          </li>
        ))}
      </ul>
      <h2>New Task</h2>
      <form onSubmit={handleAdd}>
        <input
          value={text}
          onChange={(event) => setText(event.target.value)}
          required
        />
        <button type="submit">Add</button>
      </form>
    </>
  );
}
