// frontends/vue/src/components/Todo.vue
<script setup>
import { deleteTodo, updateTodo } from "todos-client";
import { ref } from "vue";

const props = defineProps(["todo"]);
const emit = defineEmits(["onChange"]);
const editing = ref(false);
const text = ref(props.todo.text);

function handleUpdate() {
  updateTodo(props.todo.id, { text: text.value })
    .then(() => emit("onChange"))
    .catch(() => {
      alert("Failed to update");
    });
  editing.value = false;
}

function handleCheck(event) {
  updateTodo(props.todo.id, { done: event.target.checked })
    .then(() => emit("onChange"))
    .catch(() => {
      alert("Failed to check");
    });
}

function handleDelete() {
  deleteTodo(props.todo.id)
    .then(() => emit("onChange"))
    .catch(() => {
      alert("Failed to delete");
    });
}
</script>

<template>
  <div>
    <form @submit.prevent="handleUpdate" v-if="editing">
      <input v-model="text" required />
      <button>Update</button>
    </form>
    <div v-else>
      <input
        :id="todo.id"
        type="checkbox"
        :checked="todo.done"
        @change="handleCheck"
      />
      <label :for="todo.id">{{ todo.text }}</label>
    </div>

    <button type="button" @click="editing = !editing">
      {{ editing ? "Cancel" : "Edit" }}
    </button>
    <button type="button" @click="handleDelete">Delete</button>
  </div>
</template>

// frontends/angular/src/app/todo/todo.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
} from "@angular/core";
import { deleteTodo, updateTodo, Todo } from "todos-client";
import { FormControl, FormGroup } from "@angular/forms";

@Component({
  selector: "app-todo",
  template: `
    <div>
      <form
        (ngSubmit)="handleUpdate()"
        [formGroup]="editGroup"
        *ngIf="editing; else check"
      >
        <input formControlName="text" required />
        <button type="submit">Update</button>
      </form>
      <ng-template #check>
        <div>
          <input
            [id]="todo.id"
            type="checkbox"
            [checked]="todo.done"
            (change)="handleCheck($event)"
          />
          <label [for]="todo.id">{{ todo.text }}</label>
        </div>
      </ng-template>

      <button (click)="editing = !editing">
        {{ editing ? "Cancel" : "Edit" }}
      </button>
      <button (click)="handleDelete()">Delete</button>
    </div>
  `,
  styles: [],
})
export class TodoComponent implements OnChanges {
  @Input() todo: Todo = { id: "" };
  @Output() onChange = new EventEmitter();

  editing = false;
  editGroup = new FormGroup({
    text: new FormControl(this.todo.text),
  });

  ngOnChanges(changes: SimpleChanges) {
    this.editGroup.setValue({ text: this.todo.text });
  }

  handleUpdate() {
    updateTodo(this.todo.id, this.editGroup.value)
      .then(() => this.onChange.emit())
      .catch(() => {
        alert("Failed to update");
      });
    this.editing = false;
  }

  handleCheck(event: Event) {
    updateTodo(this.todo.id, {
      done: (event.target as HTMLInputElement).checked,
    })
      .then(() => this.onChange.emit())
      .catch(() => {
        alert("Failed to check");
      });
  }

  handleDelete() {
    deleteTodo(this.todo.id)
      .then(() => this.onChange.emit())
      .catch(() => {
        alert("Failed to delete");
      });
  }
}
